//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAMUP_FRAMEWORK_WEBFORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public memberTBL()
        {
            this.drawingTBLs = new HashSet<drawingTBL>();
        }
    
        public string memberID { get; set; }
        public string memberPwd { get; set; }
        public string memberEmail { get; set; }
        public string memberName { get; set; }
        public System.DateTime memberDOB { get; set; }
        public string memberPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<drawingTBL> drawingTBLs { get; set; }
    }
}
